/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f8f9ff",
        "secondary-fixed-dim": "#adc6ff",
        "primary-container": "#8455ef",
        "surface-container-high": "#dce9ff",
        "tertiary-fixed-dim": "#4edea3",
        "surface-tint": "#6d3bd7",
        "surface-container": "#e5eeff",
        "primary": "#6b38d4",
        "on-tertiary-fixed": "#002113",
        "on-primary-fixed-variant": "#5516be",
        "surface-variant": "#d3e4fe",
        "tertiary": "#006947",
        "primary-fixed-dim": "#d0bcff",
        "inverse-primary": "#d0bcff",
        "surface-container-low": "#eff4ff",
        "secondary": "#0058be",
        "tertiary-container": "#00855b",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#e9ddff",
        "on-primary-container": "#fffbff",
        "error-container": "#ffdad6",
        "surface-bright": "#f8f9ff",
        "on-tertiary-fixed-variant": "#005236",
        "outline-variant": "#cbc3d7",
        "on-secondary": "#ffffff",
        "surface": "#f8f9ff",
        "on-primary-fixed": "#23005c",
        "inverse-surface": "#213145",
        "on-background": "#0b1c30",
        "on-secondary-container": "#fefcff",
        "on-secondary-fixed-variant": "#004395",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#494454",
        "secondary-container": "#2170e4",
        "on-surface": "#0b1c30",
        "surface-dim": "#cbdbf5",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#001a42",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "surface-container-highest": "#d3e4fe",
        "tertiary-fixed": "#6ffbbe",
        "on-error": "#ffffff",
        "outline": "#7b7486",
        "secondary-fixed": "#d8e2ff",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-container": "#f5fff6"
      },
      spacing: {
        "margin-mobile": "16px",
        "base": "4px",
        "gutter": "24px",
        "lg": "40px",
        "xl": "64px",
        "md": "24px",
        "sm": "16px",
        "xs": "8px",
        "container-max": "1200px"
      }
    },
  },
  plugins: [],
}
